hyperparams:
  batch_size: 100
  t0: 0.0
  t1: 20.0
  dt: 0.05
  method: "euler"
  device: "cpu"
  sample_no: 100
  step_size: 10
  max_iter: 30
  k_range: 50
  random_seed: 42
  finite_eps: 1e-12
system_params:
  base: 50
  max_ss_dev: 0.5
  max_nadir_dev: 0.8
  max_rocof: 1
  delta_P: -0.12
  tau: 10.0
  r: 0.06
  M0: 6.0
  D0: 5.0